project 'hackNight.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hackNight' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'JSQMessagesViewController'
  pod 'SparkSDK'

  pod 'SDWebImage'
  # Pods for hackNight

end
